### PR TITLE
Fix Drake deprecation warnings

### LINKED ISSUE #10: Fix deprecation warnings from nightly Drake
After building with Drake's nightly binaries on Focal 20.04 on `rolling`, I encountered a few Drake API deprecation warnings in  RosSubscriberSystem:

```
--- stderr: drake_ros_core
/home/robot/workspace/src/drake_ros_core/ros_subscriber_system.cpp: In constructor ‘drake_ros_core::RosSubscriberSystem::RosSubscriberSystem(std::unique_ptr<drake_ros_core::SerializerInterface>&, const string&, const rclcpp::QoS&, std::shared_ptr<drake_ros_core::DrakeRosInterface>)’:
/home/robot/workspace/src/drake_ros_core/src/ros_subscriber_system.cpp:74:6: error: ‘drake::systems::LeafOutputPort<T>& drake::systems::LeafSystem<T>::DeclareAbstractOutputPort(typename drake::systems::LeafOutputPort<T>::AllocCallback, typename drake::systems::LeafOutputPort<T>::CalcCallback, std::set<drake::TypeSafeIndex<drake::systems::DependencyTag> >) [with T = double; typename drake::systems::LeafOutputPort<T>::AllocCallback = std::function<std::unique_ptr<drake::AbstractValue>()>; typename drake::systems::LeafOutputPort<T>::CalcCallback = std::function<void(const drake::systems::Context<double>&, drake::AbstractValue*)>]’ is deprecated: \nDRAKE DEPRECATED: Pass a port name as the first argument.\nThe deprecated code will be removed from Drake on or after 2021-10-01. [-Werror=deprecated-declarations]
   74 |     });
      |      ^
In file included from /home/robot/workspace/src/drake_ros_core/include/drake_ros_core/ros_subscriber_system.hpp:17,
                 from /home/robot/workspace/src/drake_ros_core/src/ros_subscriber_system.cpp:21:
/opt/drake/include/drake/systems/framework/leaf_system.h:1655:22: note: declared here
 1655 |   LeafOutputPort<T>& DeclareAbstractOutputPort(
      |                      ^~~~~~~~~~~~~~~~~~~~~~~~~
/home/robot/workspace/src/drake_ros_core/src/ros_subscriber_system.cpp: In member function ‘virtual void drake_ros_core::RosSubscriberSystem::DoCalcNextUpdateTime(const drake::systems::Context<double>&, drake::systems::CompositeEventCollection<double>*, double*) const’:
/home/robot/workspace/src/drake_ros_core/src/ros_subscriber_system.cpp:128:53: error: ‘void drake::systems::EventCollection<EventType>::add_event(std::unique_ptr<_Tp>) [with EventType = drake::systems::UnrestrictedUpdateEvent<double>]’ is deprecated: \nDRAKE DEPRECATED: Use AddEvent instead.\nThe deprecated code will be removed from Drake on or after 2021-09-01. [-Werror=deprecated-declarations]
  128 |       drake::systems::TriggerType::kTimed, callback));
      |                                                     ^
In file included from /opt/drake/include/drake/systems/framework/system.h:27,
                 from /opt/drake/include/drake/systems/framework/leaf_system.h:29,
                 from /home/robot/workspace/src/drake_ros_core/include/drake_ros_core/ros_subscriber_system.hpp:17,
                 from /home/robot/workspace/src/drake_ros_core/src/ros_subscriber_system.cpp:21:
/opt/drake/include/drake/systems/framework/event_collection.h:138:16: note: declared here
  138 |   virtual void add_event(std::unique_ptr<EventType> event) = 0;
      |                ^~~~~~~~~
cc1plus: all warnings being treated as errors

```

I will be updating this repo with a Dockerized build and CI to catch these warnings.

### PR DESCRIPTION
**Pull request by IanTheEngineer**
After building with Drake's nightly binaries on Focal 20.04 on `rolling`, I encountered a few Drake API deprecation warnings. These updates fix the warnings. I'll have a Docker build and CI working shortly to make these warnings more obvious as they happen  in realtime.

Together with #12 this will resolve #10.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/11)

### CODE REVIEW

**Review by IanTheEngineer — COMMENTED** [review]
+@sloretz for review please. cc @hidmic as FYI.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/11#-:-MhG0feM30svXuc8tRWx:b-328pxw)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @sloretz)

File: drake_ros_core/src/ros_subscriber_system.cpp [hunk 1]
```diff
@@ -67,6 +67,7 @@ RosSubscriberSystem::RosSubscriberSystem(
     std::bind(&RosSubscriberSystemPrivate::handle_message, impl_.get(), std::placeholders::_1));
 
   DeclareAbstractOutputPort(
+    topic_name,
```
Comment (sloretz) [inline drake_ros_core/src/ros_subscriber_system.cpp:70]: [`LcmSubscriberSystem` uses `drake::systems::kUseDefaultName` here](https://github.com/RobotLocomotion/drake/blob/1df1c47241ae0c9ce1f45198cbb6ce0abcbb1269/systems/lcm/lcm_subscriber_system.cc#L50). I'd recommend using that instead.

It's also using a new method `DeclareStateOutputPort` as of https://github.com/RobotLocomotion/drake/pull/15563 which says it avoids downstream systems from unnecessarily recalculating stuff. Maybe that'd be a good thing to make `RosSubscriberSystem` use in a follow up PR.

Comment (sloretz) [reply drake_ros_core/src/ros_subscriber_system.cpp:70]: See #12 for an alternative to this change

Comment (IanTheEngineer) [reply drake_ros_core/src/ros_subscriber_system.cpp:70]: Those are both excellent points. Thanks for the PR!

Comment (IanTheEngineer) [reply drake_ros_core/src/ros_subscriber_system.cpp:70]: I would prefer to keep this library and close to in sync with `LcmSubscriberSystem` as possible.

**Review by sloretz — APPROVED** [review]

**Review by sloretz — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/11#-:-MhPydoW9k5pjsdqFn7-:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @IanTheEngineer)
